// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://quggicqvqqrgmpiwfaon.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1Z2dpY3F2cXFyZ21waXdmYW9uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM3MTgyNjEsImV4cCI6MjA1OTI5NDI2MX0.F-q7WAMnZsSX6uIj2k7cRth-PylY8nn4uMy7zIVBVf8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);